export const TEXT = {
  HOME: {
    title: "Making Virtual Tours Simple.",
    desc: `VROO Is India's First 360 Virtual Reality Tour Online Publishing
        Platform.`
  },
  LOADING_TEXT:'Loading...',
  FORGOT_PASSWORD_BTN:'Forgot password?',
  GET_STARTED: "Get Started",
  SIGN_IN_BTN: "Sign In",
  SIGN_UP_BTN: "Sign Up",
  SIGN_UP_LINK: "Don't have an account? Sign Up",
  SIGN_IN_LINK: "Already have an account? Sign in",
  FORGOT_PASSWORD_LINK: "Forgot Password?",
  REMEMBER_ME_LABEL: "Remember me",
  BACK: "Back",
  NEW_TOUR: "New Tour",
  TEMPLATES: "Templates",
  TOURS : 'Tours',
  UNTITLED_TOUR:"Untitled Tour",
  TOUR_LINK:'Tour Link',
  SHARE:'Share',
  WELCOME_TITTLE : 'Welcome to VROO.',
  WELCOME_DESC : `India's First 360 Virtual Reality Tour Online Publishing Platform.`,
  FIRST_NAME:'First Name',
  LAST_NAME:'Last Name',
  EMAIL:'Email',
  PASSWORD:'Password',
  OLD_PASSWORD:'Old Password',
  CONFIRM_PASSWORD:'Confirm Password',
  REMEMBER_ME_DESC:'I want to receive inspiration, marketing promotions and updates via email.',
  NOT_FOUND : 'Opps! Page does not found.',
  ERROR_404 : '404 Error',
  LOGOUT_BTN : 'Logout',
  TERMS_AND_CONDITION_LABEL :'I have carefully reviewed and understood updated Terms and Conditions and Privacy Policy',
  MIN_PASSWORD_LENGTH_ERROR_MSG : 'Password can not be less that 8 characters.',
  EMAIL_ERROR_MESSAGE : "Invalid email address",
  PROFILE : 'Profile',
  MY_ACCOUNRT : 'My account',
  RESET_PASSWORD:'Reset Password',
  CHANGE_PASSWORD:'Change Password',
  SUBMIT:'Submit',
  CREATE_TOUR:'Create Tour',
  TITLE : 'Title',
  DESC : 'Description',
  CHANGE_PASSWORD_SUCCESS_TEXT:'Password has been successfully changed.',
  PASSWORD_DOES_NOT_MATCH_ERROR_MESSAGE:'New passsword and confirm password and does not match.'
};
