export const TOUR_TYPES =  {
    SIMPLE_VIRTUAL_TOUR:'SIMPLE_VIRTUAL_TOUR',
    INTERACTIVE_VIRTUAL_TOUR : 'INTERACTIVE_VIRTUAL_TOUR',
    INTERACTIVE_VIRTUAL_TOUR_WITH_HOT_SPOTS : 'INTERACTIVE_VIRTUAL_TOUR_WITH_HOT_SPOTS'
}